run_from = ENV['RUN_FROM'] == 'maven' ? 'maven' : 'vagrant'
puts "Run from #{run_from}!"

useCustomDb = ENV['useCustomDb']
useCustomDb ||= 'false'
puts "Use Custom DB #{useCustomDb}"

Vagrant.configure('2') do |config|
  config.vm.box = 'foros-without-ui'
  config.vm.box_url = 'http://maven.ocslab.com/repository/vagrant.boxes/centos64-x86_64-20140116-foros-without-ui.box'

  config.vm.network :forwarded_port, :guest => 10643, :host => 10643 # domain change
  config.vm.network :forwarded_port, :guest => 10543, :host => 10543 # Target RTB balancer
  config.vm.network :forwarded_port, :guest => 10449, :host => 10449 # static content provider Target RTB http
  config.vm.network :forwarded_port, :guest => 10448, :host => 10448 # static content provider Target RTB https
  config.vm.network :forwarded_port, :guest => 10445, :host => 10445 # static content provider http
  config.vm.network :forwarded_port, :guest => 10444, :host => 10444 # static content provider https
  config.vm.network :forwarded_port, :guest => 10443, :host => 10443 # balancer
  config.vm.network :forwarded_port, :guest => 9009, :host => 9009 # glassfish debug
  config.vm.network :forwarded_port, :guest => 8181, :host => 8181 # glassfish ui https
  config.vm.network :forwarded_port, :guest => 8080, :host => 8080 # glassfish ui http
  config.vm.network :forwarded_port, :guest => 4848, :host => 4848 # glassfish admin
  
  config.vm.provision :shell, :path => 'bootstrap.sh', :args => "#{run_from} #{useCustomDb}"
  
  config.vm.synced_folder '../..', '/project'

  config.vm.provider :virtualbox do |vb|
     # Don't boot with headless mode
     vb.gui = false
  	 
	 vb.customize ['modifyvm', :id, '--memory', '4096']

	 # Resolve external domains like ya.ru
	 vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
   end
end
