package com.foros;

public interface Contexts {

    String DEFAULT_ROOT_CONTEXT_LOCATION = "/root-test-context.xml";
    String DEFAULT_ROOT_PROPERTIES_LOCATION = "/root-test-properties.xml";
    String DEFAULT_TEST_CONTEXT_LOCATION = "/test-context.xml";

    String[] DEFAULT_ROOT_CONTEXT_LOCATIONS = {DEFAULT_ROOT_PROPERTIES_LOCATION, DEFAULT_ROOT_CONTEXT_LOCATION};
    String[] DEFAULT_CONTEXT_LOCATIONS = {DEFAULT_ROOT_PROPERTIES_LOCATION, DEFAULT_ROOT_CONTEXT_LOCATION, DEFAULT_TEST_CONTEXT_LOCATION};

}
